title: Lab Manager Resources
description: Resources to aid in the educational development of my replacement. Management resources only.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
